### ISSUE TITLE
Please don't use magic number(s)

### ISSUE THREAD

**Issue by vitalk** [GithubHungry/LeverXPython#5]
https://github.com/GithubHungry/LeverXPython/blob/ae06b9ec42cc67bff8fd4f5673eadea730c09444/Day1/Task2_v2.py#L52

What is 518?

Please give your variables meaningful self-describing names.

**Comment by GithubHungry** [comment]
![NAm3gTocNpM](https://user-images.githubusercontent.com/47281257/67955895-505f4380-fc04-11e9-9fb2-79e8d6762b3d.jpg)
 Ну не магия ли это )

**Comment by GithubHungry** [comment]
complete
